ELM/Models/Employee.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string PwdKey { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<int> LeToDays { get; set; }
        public bool IsAvail { get; set; }
        public bool IsActive { get; set; }
        public int FK_Gender { get; set; }
        public Nullable<int> FK_Designation { get; set; }
        public int FK_Section { get; set; }
        public Nullable<int> FK_EmpRole { get; set; }
        public Nullable<System.DateTime> UDT { get; set; }
    }
}

ELM/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ELM.Models;

namespace ELM.Controllers
{
    [SessionAuth]
    public class EmployeesController : Controller
    {
        private ELMEntities db = new ELMEntities();

        // GET: Employees
        public ActionResult Index()
        {
            return View(db.vwEmployees.ToList());
        }

        public ActionResult LeaveProccess()
        {
            return View();
        }

        public ActionResult IsAvailForLeaveEmployee()
        {
            string query = "EXEC SP_IsAvailForLeave_Employee"; //Execute Stored Procedure Command
            db.Database.ExecuteSqlCommand(query); //Execute in Database
            return Json(1, JsonRequestBehavior.AllowGet); //Return Json alwayes Yes
        }

        public ActionResult InsertFromEmployee(string Year, string LT)
        {
            string query = "EXEC SP_InsertFrom_Employee @StartYear='" + Year + "', @LeTypes='" + LT + "'"; //Execute Stored Procedure Command
            db.Database.ExecuteSqlCommand(query); //Execute in Database
            return Json(1, JsonRequestBehavior.AllowGet); //Return Json alwayes Yes
        }
        
       public ActionResult CalcLeaveBalanceLeAppsSum(string Year)
        {
            string query = "SP_Calc_Leave_Balance_LeAppsSum @StartYear='"+Year+"'"; //Execute Stored Procedure Command
            db.Database.ExecuteSqlCommand(query); //Execute in Database
            return Json(1, JsonRequestBehavior.AllowGet); //Return Json alwayes Yes
        }
        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.FK_Gender = new SelectList(db.Genders, "ID", "GenderType");
            ViewBag.FK_Designation = new SelectList(db.Designations, "ID", "DesignationM");
            ViewBag.FK_Section = new SelectList(db.Sections, "ID", "SectionName");
            ViewBag.FK_EmpRole = new SelectList(db.Roles, "ID", "RoleName");
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,EmpId,EmpName,PwdKey,JoiningDate,ConfirmDate,LeToDays,IsAvail,IsActive,FK_Gender,FK_Designation,FK_Section,FK_EmpRole,UDT")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.IsActive = true;
                employee.UDT = System.DateTime.Now;
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FK_Gender = new SelectList(db.Genders, "ID", "GenderType");
            ViewBag.FK_Designation = new SelectList(db.Designations, "ID", "DesignationM");
            ViewBag.FK_Section = new SelectList(db.Sections, "ID", "SectionName");
            ViewBag.FK_EmpRole = new SelectList(db.Roles, "ID", "RoleName");
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_Gender = new SelectList(db.Genders, "ID", "GenderType");
            ViewBag.FK_Designation = new SelectList(db.Designations, "ID", "DesignationM");
            ViewBag.FK_Section = new SelectList(db.Sections, "ID", "SectionName");
            ViewBag.FK_EmpRole = new SelectList(db.Roles, "ID", "RoleName");
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,EmpId,EmpName,PwdKey,JoiningDate,ConfirmDate,LeToDays,IsAvail,IsActive,FK_Gender,FK_Designation,FK_Section,FK_EmpRole,UDT")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.UDT = System.DateTime.Now;
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FK_Gender = new SelectList(db.Genders, "ID", "GenderType");
            ViewBag.FK_Designation = new SelectList(db.Designations, "ID", "DesignationM");
            ViewBag.FK_Section = new SelectList(db.Sections, "ID", "SectionName");
            ViewBag.FK_EmpRole = new SelectList(db.Roles, "ID", "RoleName");
            return View(employee);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ELM/Views/Employees/Create.cshtml
@model ELM.Models.Employee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-10">
        <h4>New Employee</h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmpId, "Emp Id",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpId, new { htmlAttributes = new { @class = "form-control" ,onchange= "copyIdtoText();" ,required="required", placeholder="Employee Id"} })
                @Html.ValidationMessageFor(model => model.EmpId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpName,"Full Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Employee Name" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PwdKey,"Pass", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PwdKey, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Login Pass",@readonly="readonly" } })
                @Html.ValidationMessageFor(model => model.PwdKey, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JoiningDate,"Join Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JoiningDate, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Join Date 01-Jan-2015" } })
                @Html.ValidationMessageFor(model => model.JoiningDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ConfirmDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeToDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeToDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeToDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAvail)
                    @Html.ValidationMessageFor(model => model.IsAvail, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Gender, "Gender",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Gender, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Designation,"Designation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Designation, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Section,"Section", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Section, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Section, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_EmpRole,"Role", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_EmpRole, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_EmpRole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<script>
    function copyIdtoText() {
        document.getElementById('PwdKey').value = document.getElementById('EmpId').value;
    }
</script>

ELM/Views/Employees/Edit.cshtml
@model ELM.Models.Employee

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-6">
        <h4>Edit Employee</h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.PwdKey)
        @Html.HiddenFor(model => model.ConfirmDate)
        @Html.HiddenFor(model => model.LeToDays)
        @Html.HiddenFor(model => model.IsAvail)
        <div class="form-group">
            @Html.LabelFor(model => model.EmpId, "Emp Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpId, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Employee Id" } })
                @Html.ValidationMessageFor(model => model.EmpId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmpName, "Full Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmpName, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Employee Name" } })
                @Html.ValidationMessageFor(model => model.EmpName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.JoiningDate, "Join Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JoiningDate, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Join Date 01-Jan-2015" } })
                @Html.ValidationMessageFor(model => model.JoiningDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FK_Gender, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Gender, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Designation, "Designation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Designation, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Section, "Section", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Section, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Section, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_EmpRole, "Role", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_EmpRole, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_EmpRole, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, "Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

ELM/Views/Employees/Index.cshtml
@model IEnumerable<ELM.Models.vwEmployee>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <p>
                    @Html.ActionLink("Add New", "Create")
                </p>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="table1">
                        <thead>
                            <tr>
                                <th>
                                    E Id
                                </th>
                                <th>
                                    E Name
                                </th>
                                <th>
                                    Joining Date
                                </th>
                                <th>
                                    Confirm Date
                                </th>
                                <th>
                                    L Avail
                                </th>
                                <th>
                                    L Status
                                </th>
                                <th>
                                    E Status
                                </th>
                                <th>
                                    Gender
                                </th>
                                <th>
                                    Designation
                                </th>
                                <th>
                                    Section
                                </th>
                                <th>
                                    Department
                                </th>
                                <th>
                                    Role
                                </th>
                                <th>#</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EmpId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EmpName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.JoiningDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ConfirmDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LeToDays)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IsAvail)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IsActive)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.GenderType)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DesignationM)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.SectionName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DepartmentName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RoleName)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Employees", new { id = item.ID})" onclick="return confirm('Are you sure you want to Edit?')" class="btn btn-sm btn-primary">
                                            <i class="fa fa-check-circle"></i><span>
                                                <strong> Edit</strong>
                                            </span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#table1').DataTable({
                responsive: true
            });
        });
    </script>
}

ELM/Views/Employees/LeaveProccess.cshtml
@{
    ViewBag.Title = "LeaveProccess";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Leave Proccess</h4>
<div class="row">
    <div class="col-lg-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                Who is Avail ?
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <a class="btn btn-sm btn-primary" href="#" onclick="IsAvailForLeaveEmployee();">Avail For Leave : Employee</a>
                </div>
            </div>
            <div class="panel-footer">
                for Employee (1)
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
    <div class="col-lg-8">
        <div class="panel panel-info">
            <div class="panel-heading">
                Avail for Leave
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-4">
                        <select id="rpt1" class="form-control">
                            <option value="">--Select an year--</option>
                            <option value="2019">2019</option>
                            <option value="2020">2020</option>
                            <option value="2021">2021</option>
                            <option value="2022">2022</option>
                            <option value="2023">2023</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <select id="rpt2" class="form-control">
                            <option value="">--Select a Leave--</option>
                            <option value="SL">Sick Leave</option>
                            <option value="CL">Casual Leave</option>
                            <option value="EL">Earn Leave</option>
                        </select>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-sm btn-primary" href="#" onclick="InsertFromEmployee();">Add to Leave List : Employee</a>
                    </div>
                </div>

            </div>
            <div class="panel-footer">
               Add Employee to Leave List (2)
            </div>
        </div>
    </div>
</div>
<!-- /.col-lg-4 -->
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-info">
            <div class="panel-heading">
                Calculate current balance ?
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-6">
                        <select id="rpt3" class="form-control">
                            <option value="">--Select an year--</option>
                            <option value="2019">2019</option>
                            <option value="2020">2020</option>
                            <option value="2021">2021</option>
                            <option value="2022">2022</option>
                            <option value="2023">2023</option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <a class="btn btn-sm btn-primary" href="#" onclick="CalcLeaveBalanceLeAppsSum();">Calculate Rest Leave : Employee</a>
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                after leave (3)
            </div>
        </div>
    </div>
    <!-- /.col-lg-4 -->
</div>


<script>
    //Call A function using Ajax
    function IsAvailForLeaveEmployee() {
        $.post("@Url.Action("IsAvailForLeaveEmployee", "Employees")",
    function (data) {
        if (data == 0) {
            alert("Process Failed");
            location.reload();
        }
        else {
            alert("Process Completed");
            location.reload();
        }
    })
    };

    function InsertFromEmployee() {
        var rpt1 = document.getElementById('rpt1').value;
        var rpt2 = document.getElementById('rpt2').value;
        if (rpt1 != "" && rpt2 != "") {
            $.post("@Url.Action("InsertFromEmployee", "Employees")", {Year: rpt1, LT: rpt2},
            function (data) {
                if (data == 0) {
                    alert("Process Failed");
                    location.reload();
                }
                else {
                    alert("Process Completed");
                    location.reload();
                }
            })
        } else {
            alert("Select a valid data");
        }
    };

    function CalcLeaveBalanceLeAppsSum() {
        var rpt3 = document.getElementById('rpt3').value;
        if (rpt3 != "" ) {
        $.post("@Url.Action("CalcLeaveBalanceLeAppsSum", "Employees")", {Year: rpt3},
        function (data) {
            if (data == 0) {
                alert("Process Failed");
                location.reload();
            }
            else {
                alert("Process Completed");
                location.reload();
            }
        })
        } else {
            alert("Select a valid data");
        }
    };
</script>