ELM/Controllers/LeaveApplicationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ELM.Models;

namespace ELM.Controllers
{
    [SessionAuth]
    public class LeaveApplicationController : Controller
    {
        private ELMEntities db = new ELMEntities();

        // GET: LeaveApplication
        public ActionResult Index()
        {
            if (Session["EmpIdpk"] != null)
            {
                int EmpID = Convert.ToInt32(Session["EmpIdpk"]);
                var LBalance = db.LeAppsSums.Where(l => l.FK_Employee.Equals(EmpID)).ToList();
                if (LBalance != null || LBalance.Count() != 0)
                {
                    var SSL = LBalance.Where(s => s.FK_LeTitle.Equals(1)).ToList();
                    if (SSL.Count() != 0)
                    {
                        ViewBag.SL = SSL.FirstOrDefault().LeBalance;
                        ViewBag.SL1 = SSL.FirstOrDefault().LeUsed;
                    }
                    var CCL = LBalance.Where(s => s.FK_LeTitle.Equals(3)).ToList();
                    if (CCL.Count() != 0)
                    {
                        ViewBag.CL = CCL.FirstOrDefault().LeBalance;
                        ViewBag.CL1 = CCL.FirstOrDefault().LeUsed;
                    }
                    var EEL = LBalance.Where(s => s.FK_LeTitle.Equals(2)).ToList();
                    if (EEL.Count() != 0)
                    {
                        ViewBag.EL = EEL.FirstOrDefault().LeBalance;
                        ViewBag.EL1 = EEL.FirstOrDefault().LeUsed;
                    }
                }
                return View(db.LeApps.Where(a => a.FK_Employee == EmpID).ToList());
            }
            else
            {
                return RedirectToAction("Logout", "Home");
            }
        }

        // GET: LeaveApplication/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LeApp leApp = db.LeApps.Find(id);
            if (leApp == null)
            {
                return HttpNotFound();
            }
            return View(leApp);
        }

        // GET: LeaveApplication/Create
        public ActionResult Create()
        {
            if (Session["EmpIdpk"] != null)
            {
                int EmpID = Convert.ToInt32(Session["EmpIdpk"]);
                ViewBag.FK_Employee = new SelectList(db.Employees.Where(e => e.ID == EmpID), "ID", "EmpName");
                ViewBag.FK_LeTitle = new SelectList(db.LeTitles, "ID", "LeType");
                return View();
            }
            else
            {
                return RedirectToAction("Logout", "Home");
            }

        }
        // POST: LeaveApplication/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FromDates,ToDates,LYear,LeQty,LeaveReason,WreStayInLeave,LeDocuments,DocName,DocNameNew,IsHalfLe,FK_Employee,FK_LeTitle,FK_ApproverA,ApproverA,FK_ApproverB,ApproverB,IsRejected,UDT")] LeApp leApp)
        {
            int EmpID = Convert.ToInt32(Session["EmpIdpk"]);

            var LQty = (leApp.ToDates - leApp.FromDates).TotalDays;
            if (LQty == 0) //if set single date make it 1 day
            {
                LQty = 1;
            }
            if (LQty < 0)
            {
                ViewBag.Err = "Sorry!. Negetive days not applied";
                ViewBag.FK_Employee = new SelectList(db.Employees.Where(e => e.ID == EmpID), "ID", "EmpName");
                ViewBag.FK_LeTitle = new SelectList(db.LeTitles, "ID", "LeType");
                return View(leApp);
            }
            LQty = LQty + 1;
            bool IsHalf = false;
            if (leApp.IsHalfLe == null)
            {
                IsHalf = false;
            }
            else if (leApp.IsHalfLe == false)
            {
                IsHalf = false;
            }
            else
            {
                IsHalf = true;
                if (LQty == 1)
                {
                    LQty = 0.5; //if today half leave
                }
                else
                {
                    LQty = LQty - 0.5; //if today half but past days are full leave
                }
            }
            //caculate before apply leave
            var LBalance = db.LeAppsSums.Where(l => l.FK_Employee.Equals(leApp.FK_Employee) && l.FK_LeTitle.Equals(leApp.FK_LeTitle)).ToList();
            if (LBalance.Count() != 0)
            {
                var Balance = LBalance.FirstOrDefault().LeBalance;
                var Used = LBalance.FirstOrDefault().LeUsed;
                var Sum = Balance - Used;
                if (Convert.ToDecimal(LQty) > Sum)
                {
                    ViewBag.Err = "Sorry!. You have not enough balance.";
                    ViewBag.FK_Employee = new SelectList(db.Employees.Where(e => e.ID == EmpID), "ID", "EmpName");
                    ViewBag.FK_LeTitle = new SelectList(db.LeTitles, "ID", "LeType");
                    return View(leApp);
                }
            }
            else
            {
                ViewBag.FK_Employee = new SelectList(db.Employees.Where(e => e.ID == EmpID), "ID", "EmpName");
                ViewBag.FK_LeTitle = new SelectList(db.LeTitles, "ID", "LeType");
                ViewBag.Err = "Sorry!. You have not enough balance.";
                return View(leApp);
            }
            if (ModelState.IsValid)
            {
                leApp.LeQty = Convert.ToDecimal(LQty);
                leApp.LYear = System.DateTime.Now.Year;
                leApp.UDT = System.DateTime.Now;
                leApp.IsHalfLe = IsHalf;
                db.LeApps.Add(leApp);
                db.SaveChanges();
                //Execute Procedure
                SP_Single_Leave_Plus_LeAppsSum(leApp.LeQty, leApp.LYear, leApp.FK_Employee, leApp.FK_LeTitle);
                return RedirectToAction("Index");
            }

            ViewBag.FK_Employee = new SelectList(db.Employees.Where(e => e.ID == EmpID), "ID", "EmpName");
            ViewBag.FK_LeTitle = new SelectList(db.LeTitles, "ID", "LeType");
            return View(leApp);
        }

        // GET: LeaveApplication/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LeApp leApp = db.LeApps.Find(id);
            if (leApp == null)
            {
                return HttpNotFound();
            }
            return View(leApp);
        }

        // POST: LeaveApplication/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FromDates,ToDates,LYear,LeQty,LeaveReason,WreStayInLeave,LeDocuments,DocName,DocNameNew,IsHalfLe,FK_Employee,FK_LeTitle,FK_ApproverA,ApproverA,FK_ApproverB,ApproverB,IsRejected,UDT")] LeApp leApp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leApp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(leApp);
        }

        //Delete L App
        public ActionResult Revoke(long id)
        {
            LeApp leApp = db.LeApps.Find(id);
            db.LeApps.Remove(leApp);
            db.SaveChanges();
            //Execute Procedure
            SP_Single_Leave_Minus_LeAppsSum(leApp.LeQty, leApp.LYear, leApp.FK_Employee, leApp.FK_LeTitle);
            return RedirectToAction("Index");
        }
        //Multiple L App [GET]
        public ActionResult MoreLeaveApply()
        {
            if (Session["EmpIdpk"] != null)
            {
                int EmpID = Convert.ToInt32(Session["EmpIdpk"]);
                ViewBag.FK_Employee = new SelectList(db.Employees.Where(e => e.ID == EmpID), "ID", "EmpName");
                return View();
            }
            else
            {
                return RedirectToAction("Logout", "Home");
            }
        }
        //Multiple L App [POST]
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult MoreLeaveApply([Bind(Include = "CLFK_LeTitle,CLfrom,CLto,SLFK_LeTitle,SLfrom,SLto,ELFK_LeTitle,ELform,ELto,LeaveReason,WreStayInLeave,LeDocuments,IsHalfLe,FK_Employee,")] MoreLeaveApplyVM leApp)
        public ActionResult MoreLeaveApply(MoreLeaveApplyVM leApp)
        {
            int EmpID = Convert.ToInt32(Session["EmpIdpk"]);
            #region HalfLe
            //bool IsHalf = false;
            //if (leApp.IsHalfLe == null)
            //{
            //    IsHalf = false;
            //}
            //else if (leApp.IsHalfLe == false)
            //{
            //    IsHalf = false;
            //}
            //else
            //{
            //    IsHalf = true;
            //    if (LQty == 1)
            //    {
            //        LQty = 0.5; //if today half leave
            //    }
            //    else
            //    {
            //        LQty = LQty - 0.5; //if today half but past days are full leave
            //    }
            //}
            #endregion  
            #region CL

            if (leApp.CLFK_LeTitle != false)
            {
                var CL = (leApp.CLto - leApp.CLfrom).TotalDays + 1;
                if (CL == 0) //if set single date make it 1 day
                {
                    CL = 1;
                }
                //caculate before apply leave
                var CLBalance = db.LeAppsSums.Where(l => l.FK_Employee.Equals(leApp.FK_Employee) && l.FK_LeTitle.Equals(3)).ToList();
                if (CLBalance.Count() != 0)
                {
                    var Balance = CLBalance.FirstOrDefault().LeBalance;

ELM/Views/LeaveApplication/Create.cshtml
@model ELM.Models.LeApp

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-7">
        <h4>New Leave App</h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FK_LeTitle, "Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_LeTitle, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_LeTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FromDates,"From", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FromDates, new { htmlAttributes = new { @class = "form-control",required="required", placeholder = "02-Jan-2019" } })
                @Html.ValidationMessageFor(model => model.FromDates, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToDates, "To",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToDates, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "03-Jan-2019" } })
                @Html.ValidationMessageFor(model => model.ToDates, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeaveReason, "Reason",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeaveReason, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Description" } })
                @Html.ValidationMessageFor(model => model.LeaveReason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WreStayInLeave, "Where stay during leave?",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WreStayInLeave, new { htmlAttributes = new { @class = "form-control", required = "required", placeholder = "Where?" } })
                @Html.ValidationMessageFor(model => model.WreStayInLeave, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LeDocuments, "Document",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LeDocuments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LeDocuments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsHalfLe, "With Half",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsHalfLe, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsHalfLe, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Employee, "Name",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Employee, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Employee, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Apply" class="btn btn-primary" />
                @ViewBag.Err
            </div>
        </div>
    </div>
}

ELM/Views/LeaveApplication/Index.cshtml
@model IEnumerable<ELM.Models.LeApp>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Show Balance</a>
        </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-2">
                    <p>SL: @ViewBag.SL / @ViewBag.SL1</p>
                </div>
                <div class="col-md-2">
                    <p>EL: @ViewBag.EL / @ViewBag.EL1</p>
                </div>
                <div class="col-md-2">
                    <p>CL: @ViewBag.CL / @ViewBag.CL1</p>
                </div>
            </div>
        </div>
    </div>
</div>




<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="@Url.Action("Create", "LeaveApplication")" , class="btn btn-primary">
                    <i class="fa fa-plus-circle"></i><span>
                        <strong> Apply Now</strong>
                    </span>
                </a>
                <a href="@Url.Action("MoreLeaveApply", "LeaveApplication")" , class="btn btn-primary">
                    <i class="fa fa-bolt"></i><span>
                        <strong> Apply Mix</strong>
                    </span>
                </a>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover" id="table1">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>
                                    From
                                </th>
                                <th>
                                    To
                                </th>
                                <th>
                                    Days
                                </th>
                                <th>
                                    Reason
                                </th>
                                <th>
                                    Where
                                </th>
                                <th>
                                    Doc
                                </th>
                                <th>
                                    Half?
                                </th>
                                <th>
                                    1st Approve
                                </th>
                                <th>
                                    Final Approve
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @if (item.FK_ApproverA == null)
                {

                                            <a href="@Url.Action("Revoke", "LeaveApplication", new { id = item.ID})" onclick="return confirm('Are you sure you want to Delete?')" class="btn btn-primary">
                                                <i class="fa fa-trash-o"></i><span>
                                                    <strong> Del</strong>
                                                </span>
                                            </a>

                                        }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.FromDates)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ToDates)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LeQty)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LeaveReason)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.WreStayInLeave)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LeDocuments)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.IsHalfLe)
                                    </td>
                                    <td>
                                        @if (item.FK_ApproverA != null)
                {
                                            <i class="fa fa-check-circle-o"></i>
                                        }
                                    </td>
                                    <td>
                                        @if (item.FK_ApproverB != null)
                {
                                            <i class="fa fa-check-circle-o"></i>
                                        }
                                    </td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
@section scripts{
    <script>
    $(document).ready(function () {
        $('#table1').DataTable({
            responsive: true
        });
    });
</script>
    }