ELM/Models/Department.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int ID { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentNote { get; set; }
        public Nullable<System.DateTime> UDT { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}

ELM/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ELM.Models;

namespace ELM.Controllers
{
    [SessionAuth]
    public class DepartmentsController : Controller
    {
        private ELMEntities db = new ELMEntities();

        // GET: Departments Text
        public ActionResult Index()
        {
            return View(db.Departments.ToList());
        }
        
        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,DepartmentName,DepartmentNote,UDT,IsActive")] Department department)
        {
            if (ModelState.IsValid)
            {
                department.IsActive = true;
                department.UDT = System.DateTime.Now;
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,DepartmentName,DepartmentNote,UDT,IsActive")] Department department)
        {
            if (ModelState.IsValid)
            {
                department.UDT = System.DateTime.Now;
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }
        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ELM/Views/Departments/Create.cshtml
@model ELM.Models.Department

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-6">
        <h4>New Department</h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentName, "Department Name",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" ,required = "required" ,placeholder="Department Name"} })
                @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentNote,"Details", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentNote, new { htmlAttributes = new { @class = "form-control",placeholder="Detail Note" } })
                @Html.ValidationMessageFor(model => model.DepartmentNote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

ELM/Views/Departments/Edit.cshtml
@model ELM.Models.Department

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-6">
        <h4>Edit Department</h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentName,"Department Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentName, new { htmlAttributes = new { @class = "form-control" , required = "required", placeholder = "Department Name" } })
                @Html.ValidationMessageFor(model => model.DepartmentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentNote, "Detail",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentNote, new { htmlAttributes = new { @class = "form-control", placeholder = "Detail Note" } })
                @Html.ValidationMessageFor(model => model.DepartmentNote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, "Status",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive ,new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

ELM/Views/Departments/Index.cshtml
@model IEnumerable<ELM.Models.Department>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- /.col-lg-4 -->
<div class="col-lg-10">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <a class="btn btn-sm btn-default" href="@Url.Action("Create","Departments")">New Department</a>
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>
                        Department Name
                    </th>
                    <th>
                        In Details
                    </th>
                    <th>
                        Status
                    </th>
                    <th>#</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DepartmentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DepartmentNote)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsActive)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="panel-footer">
            Available Departments
        </div>
    </div>
</div>
<!-- /.col-lg-4 -->