ELM/Models/Section.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int ID { get; set; }
        public string SectionName { get; set; }
        public int FK_Department { get; set; }
        public Nullable<System.DateTime> UDT { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}

ELM/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ELM.Models;

namespace ELM.Controllers
{
    [SessionAuth]
    public class SectionsController : Controller
    {
        private ELMEntities db = new ELMEntities();

        // GET: Sections
        public ActionResult Index()
        {
            return View(db.vw_Sections.ToList());
        }

     
        // GET: Sections/Create
        public ActionResult Create()
        {
            ViewBag.FK_Department = new SelectList(db.Departments.Where(d => d.IsActive == true), "ID", "DepartmentName");
            return View();
        }

        // POST: Sections/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SectionName,FK_Department,IsActive,UDT")] Section  Sections)
        {
            if (ModelState.IsValid)
            {
                Sections.IsActive = true;
                Sections.UDT = System.DateTime.Now;
                db.Sections.Add(Sections);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FK_Department = new SelectList(db.Departments.Where(d => d.IsActive == true), "ID", "DepartmentName");
            return View(Sections);
        }

        // GET: Sections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section vw_Sections = db.Sections.Find(id);
            if (vw_Sections == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_Department = new SelectList(db.Departments.Where(d => d.IsActive == true), "ID", "DepartmentName");
            return View(vw_Sections);
        }

        // POST: Sections/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SectionName,FK_Department,IsActive,UDT")] Section Sections)
        {
            if (ModelState.IsValid)
            {
                Sections.UDT = System.DateTime.Now;
                db.Entry(Sections).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FK_Department = new SelectList(db.Departments.Where(d => d.IsActive == true), "ID", "DepartmentName");
            return View(Sections);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ELM/Views/Sections/Create.cshtml
@model ELM.Models.Section

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal col-md-6">
        <h4>New Sections</h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
               <div class="form-group">
            @Html.LabelFor(model => model.SectionName, "Section",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SectionName, new { htmlAttributes = new { @class = "form-control" , required = "required" ,placehodler="Section Name"} })
                @Html.ValidationMessageFor(model => model.SectionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Department,"Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Department, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

ELM/Views/Sections/Edit.cshtml
@model ELM.Models.Section

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal col-md-6">
        <h4>Edit Sections</h4>
        @Html.ActionLink("Back to List", "Index")
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.SectionName, "Section", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SectionName, new { htmlAttributes = new { @class = "form-control", required = "required", placehodler = "Section Name" } })
                @Html.ValidationMessageFor(model => model.SectionName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FK_Department, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.FK_Department, null, htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.FK_Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive,"Status", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

ELM/Views/Sections/Index.cshtml
@model IEnumerable<ELM.Models.vw_Sections>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- /.col-lg-4 -->
<div class="col-lg-10">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <a class="btn btn-sm btn-default" href="@Url.Action("Create","Sections")">New Section</a>
        </div>
        <div class="panel-body">
            <table class="table">
                <tr>
                    <th>
                        Section Name
                    </th>
                    <th>
                        Department
                    </th>
                    <th>
                        Status
                    </th>
                    <th>#</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.SectionName)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.DepartmentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsActive)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="panel-footer">
            Available Sections
        </div>
    </div>
</div>
<!-- /.col-lg-4 -->